const actionType = {
  ALGORITHM_APPLY: 'ALGORITHM_APPLY',
  ALGORITHM_DELETE: 'ALGORITHM_DELETE',
  ALGORITHM_STORE: 'ALGORITHM_STORE',
  ALGORITHM_GET_VERSIONS: 'ALGORITHM_GET_VERSIONS',
  AUTO_COMPLETE_UPDATE_FILTER: 'AUTO_COMPLETE_UPDATE_FILTER',
  BUILD_RERUN: 'BUILD_RERUN',
  BUILD_STOP: 'BUILD_STOP',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  CLOSE_TERMINAL_CLIENT: 'CLOSE_TERMINAL_CLIENT',
  DEBUG_ADD: 'DEBUG_ADD',
  DEBUG_DELETE: 'DEBUG_DELETE',
  JOBS_DOWNLOAD_REQ: 'JOBS_DOWNLOAD_REQ',
  JOBS_DOWNLOAD_RESULTS: 'JOBS_DOWNLOAD_RESULTS',
  JOBS_EXEC_CACHING: 'JOBS_EXEC_CACHING',
  JOBS_KUBERNETES_LOGS: 'JOBS_KUBERNETES_LOGS',
  PIPELINE_ADD: 'PIPELINE_ADD',
  PIPELINE_CRON_START: 'PIPELINE_CRON_START',
  PIPELINE_CRON_STOP: 'PIPELINE_CRON_STOP',
  PIPELINE_DELETE: 'PIPELINE_DELETE',
  PIPELINE_PAUSE: 'PIPELINE_PAUSE',
  PIPELINE_RESUME: 'PIPELINE_RESUME',
  PIPELINE_START: 'PIPELINE_START',
  PIPELINE_STOP: 'PIPELINE_STOP',
  PIPELINE_UPDATE: 'PIPELINE_UPDATE',
  README_GET_ALGORITHM: 'README_GET_ALGORITHM',
  README_GET_PIPELINE: 'README_GET_PIPELINE',
  README_POST_ALGORITHM: 'README_POST_ALGORITHM',
  README_POST_PIPELINE: 'README_POST_PIPELINE',
  REST_REQ_CONFIG: 'REST_REQ_CONFIG',
  REST_REQ_DELETE: 'REST_REQ_DELETE',
  REST_REQ_POST_FORM: 'REST_REQ_POST_FORM',
  REST_REQ_POST: 'REST_REQ_POST',
  REST_REQ_PUT: 'REST_REQ_PUT',
  REST_REQ_GET: 'REST_REQ_GET',
  REST_REQ: 'REST_REQ',
  SOCKET_GET_CONFIG: 'SOCKET_GET_CONFIG',
  SOCKET_GET_DATA: 'SOCKET_GET_DATA',
  SOCKET_SET_URL: 'SOCKET_SET_URL',
  CONNECTION_STATUS_CHANGE: 'CONNECTION_STATUS_CHANGE',
  SOCKET_INIT: 'SOCKET_INIT',
  USER_GUIDE_CHANGE_STEP: 'USER_GUIDE_CHANGE_STEP',
  USER_GUIDE_TRIGGER: 'USER_GUIDE_TRIGGER',
};

const restHelper = action => {
  actionType[`${action}_PENDING`] = `${action}_PENDING`;
  actionType[`${action}_SUCCESS`] = `${action}_SUCCESS`;
  actionType[`${action}_REJECT`] = `${action}_REJECT`;
};

restHelper(actionType.SOCKET_GET_CONFIG);
restHelper(actionType.JOBS_DOWNLOAD_RESULTS);
restHelper(actionType.JOBS_KUBERNETES_LOGS);
restHelper(actionType.ALGORITHM_APPLY);
restHelper(actionType.ALGORITHM_DELETE);
restHelper(actionType.README_GET_PIPELINE);
restHelper(actionType.README_GET_ALGORITHM);
restHelper(actionType.README_POST_PIPELINE);
restHelper(actionType.README_POST_ALGORITHM);
restHelper(actionType.ALGORITHM_GET_VERSIONS);

export default actionType;
