export default {
  ADD_PIPELINE: '120ch',
  ADD_ALGORITHM: '40vw',
  ADD_DEBUG: '20vw',
  ADD_DATASOURCE: '40vw',
  EDIT_DATASOURCE: '50vw',
  RUN_RAW_PIPELINE: '40vw',
  STORAGE: '60vw',
  CPU: '60vw',
  GPU: '60vw',
  MEMORY: '60vw',
  ERROR_LOGS: '70vw',
  JOB_INFO: '70vw',
  ALGORITHM_INFO: '70vw',
  PIPELINE_INFO: '70vw',
  ALGORITHM_EDIT: '40vw',
  TF_RUN: '30vw',
};
