export default {
  ADD_PIPELINE: '150ch',
  ADD_ALGORITHM: '160ch',
  ADD_DATASOURCE: '40vw',
  EDIT_DATASOURCE: '50vw',
  RUN_RAW_PIPELINE: '40vw',
  STORAGE: '80vw',
  CPU: '80vw',
  GPU: '80vw',
  MEMORY: '80vw',
  ERROR_LOGS: '70vw',
  JOB_INFO: '90vw',
  ALGORITHM_INFO: '160ch',
  PIPELINE_INFO: '70vw',
  ALGORITHM_EDIT: '40vw',
  TF_RUN: '30vw',
  WORKERS: '90vw',
  DRIVERS: '90vw',
};
