export const DRAWER_TITLES = {
  WORKERS: 'Workers',
  DRIVERS: 'Drivers',
  ADD_PIPELINE: 'Pipeline Wizard',
  ADD_ALGORITHM: 'Algorithm Wizard',
  ADD_MARKETPLACE: 'Marketplace Wizard',
  ADD_DATASOURCE: ' Datasource wizard',
  EDIT_DATASOURCE: ' Datasource editor',
  RUN_RAW_PIPELINE: 'Run  Pipeline',
  STORAGE: 'Storage monitor',
  CPU: 'CPU monitor',
  GPU: 'GPU monitor',
  MEMORY: 'Memory monitor',
  ERROR_LOGS: 'Log viewer',
  JOB_INFO: 'Job Overview',
  ALGORITHM_INFO: 'Algorithm Overview',
  PIPELINE_INFO: 'Pipeline Overview',
  ALGORITHM_EDIT: ' Algorithm editor',
  MARKETPLACE_EDIT: ' Marketplace editor',
  EDIT_PIPELINE: ' Pipeline editor',
  PIPELINE_EXECUTE: 'Run Pipeline',
  TF_RUN: 'TF Run',
};
