export default {
  ACTIVE: 'active',
  INIT: 'init',
  COMPLETED: 'completed',
  FAILED: 'failed',
  PAUSED: 'paused',
  PENDING: 'pending',
  RECOVERING: 'recovering',
  RESUMED: 'resumed',
  STALLED: 'stalled',
  STOPPED: 'stopped',
  STOPPING: 'stopping',
  SUCCEED: 'succeed',
  SUCCESS: 'success',
  WAITING: 'waiting',
  PRESCHEDULE: 'preschedule',
};
