// Depends on reducers/root.reducer.js

export default {
  ALGORITHM_BUILDS_TABLE: `algorithmBuildsTable`,
  ALGORITHM_TABLE: `algorithmTable`,
  ALGORITHM_VERSIONS: `algorithmVersions`,
  AUTO_COMPLETE_FILTER: `autoCompleteFilter`,
  BOARD_URL: `boardURL`,
  HKUBE_SYSTEM_VERSION: `hkubeSystemVersion`,
  BOARDS: `boards`,
  CONNECTION_STATUS: `connectionStatus`,
  DEBUG_TABLE: `debugTable`,
  DRAWER: `drawer`,
  DRIVER_TABLE: `driverTable`,
  ERROR_LOGS_TABLE: `errorLogsTable`,
  EXPERIMENTS: `experiments`,
  FILTER_TYPES: `filterByType`,
  JOBS_KUBERNETES_LOGS: `jobsKubernetesLogs`,
  JOBS_TABLE: `jobsTable`,
  NODE_STATISTICS: `nodeStatistics`,
  DISK_SPACE: `diskSpace`,
  PIPELINE_TABLE: `pipelineTable`,
  SETTINGS: `settings`,
  SOCKET_URL: `socketURL`,
  USER_GUIDE: `userGuide`,
  VIEW_TYPE: `viewType`,
  WORKER_TABLE: `workerTable`,
  META: `meta`,
};
