import { LEFT_SIDEBAR_NAMES } from './sidebar-names';

export const USER_GUIDE = {
  WELCOME: 'ug_welcome',
  HEADER: {
    AUTO_COMPLETE: 'ug_autocomplete',
    SOCIALS: 'ug_socials',
  },
  SIDEBAR_LEFT: 'ug_sidebar_left',
  SIDEBAR_LEFT_MENU_BUTTON: 'ug_sidebar_left_menu_button',
  SIDEBAR_TOP_RIGHT: 'ug_sidebar_top_right',
  SIDEBAR_BOTTOM_RIGHT: 'ug_sidebar_bottom_right',
  TABLE: 'ug_table',
  TABLE_SELECT: {
    [LEFT_SIDEBAR_NAMES.JOBS]: `ug_${LEFT_SIDEBAR_NAMES.JOBS}`,
    [LEFT_SIDEBAR_NAMES.PIPELINES]: `ug_${LEFT_SIDEBAR_NAMES.PIPELINES}`,
    [LEFT_SIDEBAR_NAMES.ALGORITHMS]: `ug_${LEFT_SIDEBAR_NAMES.ALGORITHMS}`,
    [LEFT_SIDEBAR_NAMES.WORKERS]: `ug_${LEFT_SIDEBAR_NAMES.WORKERS}`,
    [LEFT_SIDEBAR_NAMES.DRIVERS]: `ug_${LEFT_SIDEBAR_NAMES.DRIVERS}`,
    [LEFT_SIDEBAR_NAMES.DEBUG]: `ug_${LEFT_SIDEBAR_NAMES.DEBUG}`,
    [LEFT_SIDEBAR_NAMES.BUILDS]: `ug_${LEFT_SIDEBAR_NAMES.BUILDS}`,
  },
  TABLE_JOB: {
    MENU_SELECT: `ug_${LEFT_SIDEBAR_NAMES.JOBS}`,
    ID_SELECT: 'ug_job_table_id_select',
    ACTIONS_SELECT: 'ug_job_actions_select',
    ROW_SELECT: 'ug_job_row_select',
  },
};

export const userGuideStepIndexes = [
  USER_GUIDE.WELCOME,
  USER_GUIDE.HEADER.AUTO_COMPLETE,
  USER_GUIDE.HEADER.SOCIALS,
  USER_GUIDE.SIDEBAR_LEFT,
  USER_GUIDE.TABLE,
  USER_GUIDE.SIDEBAR_TOP_RIGHT,
  USER_GUIDE.SIDEBAR_BOTTOM_RIGHT,
  USER_GUIDE.TABLE_JOB.MENU_SELECT,
  USER_GUIDE.TABLE_JOB.ID_SELECT,
  USER_GUIDE.TABLE_JOB.ACTIONS_SELECT,
  USER_GUIDE.TABLE_JOB.ROW_SELECT,
];
