const restHelper = action => {
  actionType[`${action}_PENDING`] = `${action}_PENDING`;
  actionType[`${action}_SUCCESS`] = `${action}_SUCCESS`;
  actionType[`${action}_REJECT`] = `${action}_REJECT`;
};

const actionType = {
  ALGORITHM_APPLY: 'ALGORITHM_APPLY',
  ALGORITHM_DELETE: 'ALGORITHM_DELETE',
  ALGORITHM_STORE: 'ALGORITHM_STORE',
  BUILD_RERUN: 'BUILD_RERUN',
  BUILD_STOP: 'BUILD_STOP',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  CLOSE_TERMINAL_CLIENT: 'CLOSE_TERMINAL_CLIENT',
  DEBUG_ADD: 'DEBUG_ADD',
  DEBUG_DELETE: 'DEBUG_DELETE',
  JOBS_DOWNLOAD_REQ: 'JOBS_DOWNLOAD_REQ',
  JOBS_DOWNLOAD_RESULTS: 'JOBS_DOWNLOAD_RESULTS',
  JOBS_EXEC_CACHING: 'JOBS_EXEC_CACHING',
  JOBS_JAEGER: 'JOBS_JAEGER',
  JOBS_KUBERNETES_LOGS: 'JOBS_KUBERNETES_LOGS',
  LAYOUT_GET_CONFIG: 'LAYOUT_GET_CONFIG',
  LAYOUT_UPDATE_FILTER: 'LAYOUT_UPDATE_FILTER',
  LAYOUT_UPDATE_ROW_DATA_TABLE: 'LAYOUT_UPDATE_ROW_DATA_TABLE',
  PIPELINE_ADD: 'PIPELINE_ADD',
  PIPELINE_CRON_START: 'PIPELINE_CRON_START',
  PIPELINE_CRON_STOP: 'PIPELINE_CRON_STOP',
  PIPELINE_DELETE: 'PIPELINE_DELETE',
  PIPELINE_START: 'PIPELINE_START',
  PIPELINE_STOP: 'PIPELINE_STOP',
  PIPELINE_UPDATE: 'PIPELINE_UPDATE',
  README_GET_ALGORITHM: 'README_GET_ALGORITHM',
  README_GET_PIPELINE: 'README_GET_PIPELINE',
  README_POST_ALGORITHM: 'README_POST_ALGORITHM',
  README_POST_PIPELINE: 'README_POST_PIPELINE',
  REST_REQ_CONFIG: 'REST_REQ_CONFIG',
  REST_REQ_DELETE: 'REST_REQ_DELETE',
  REST_REQ_POST_FORM: 'REST_REQ_POST_FORM',
  REST_REQ_POST: 'REST_REQ_POST',
  REST_REQ_PUT: 'REST_REQ_PUT',
  REST_REQ: 'REST_REQ',
  SOCKET_INIT: 'SOCKET_INIT'
};

restHelper(actionType.LAYOUT_GET_CONFIG);
restHelper(actionType.JOBS_JAEGER);
restHelper(actionType.JOBS_DOWNLOAD_RESULTS);
restHelper(actionType.JOBS_KUBERNETES_LOGS);
restHelper(actionType.ALGORITHM_APPLY);
restHelper(actionType.ALGORITHM_DELETE);
restHelper(actionType.README_GET_PIPELINE);
restHelper(actionType.README_GET_ALGORITHM);
restHelper(actionType.README_POST_PIPELINE);
restHelper(actionType.README_POST_ALGORITHM);

export default actionType;
