import { LEFT_SIDEBAR_NAMES } from 'constants/table-names';

const USER_GUIDE = {
  WELCOME: 'ug_welcome',
  SIDEBAR_LEFT: 'ug_sidebar_left',
  SIDEBAR_LEFT_MENU_BUTTON: 'ug_sidebar_left_menu_button',
  SIDEBAR_RIGHT: 'ug_sidebar_right',
  TABLE: 'ug_table',
  TABLE_SELECT: {
    [LEFT_SIDEBAR_NAMES.JOBS]: `ug_${LEFT_SIDEBAR_NAMES.JOBS}`,
    [LEFT_SIDEBAR_NAMES.PIPELINES]: `ug_${LEFT_SIDEBAR_NAMES.PIPELINES}`,
    [LEFT_SIDEBAR_NAMES.ALGORITHMS]: `ug_${LEFT_SIDEBAR_NAMES.ALGORITHMS}`,
    [LEFT_SIDEBAR_NAMES.WORKERS]: `ug_${LEFT_SIDEBAR_NAMES.WORKERS}`,
    [LEFT_SIDEBAR_NAMES.DRIVERS]: `ug_${LEFT_SIDEBAR_NAMES.DRIVERS}`,
    [LEFT_SIDEBAR_NAMES.DEBUG]: `ug_${LEFT_SIDEBAR_NAMES.DEBUG}`,
    [LEFT_SIDEBAR_NAMES.BUILDS]: `ug_${LEFT_SIDEBAR_NAMES.BUILDS}`,
    [LEFT_SIDEBAR_NAMES.CLUSTER_STATS.CPU]: `ug_${
      LEFT_SIDEBAR_NAMES.CLUSTER_STATS.CPU
    }`,
    [LEFT_SIDEBAR_NAMES.CLUSTER_STATS.MEMORY]: `ug_${
      LEFT_SIDEBAR_NAMES.CLUSTER_STATS.MEMORY
    }`
  },
  TABLE_JOB: {
    MENU_SELECT: `ug_${LEFT_SIDEBAR_NAMES.JOBS}`,
    ID_SELECT: 'ug_job_table_id_select',
    ACTIONS_SELECT: 'ug_job_actions_select',
    ROW_SELECT: 'ug_job_row_select'
  }
};

const userGuideStepIndexes = [
  USER_GUIDE.WELCOME,
  USER_GUIDE.SIDEBAR_LEFT,
  USER_GUIDE.TABLE,
  USER_GUIDE.SIDEBAR_RIGHT,
  USER_GUIDE.TABLE_JOB.MENU_SELECT,
  USER_GUIDE.TABLE_JOB.ID_SELECT,
  USER_GUIDE.TABLE_JOB.ACTIONS_SELECT,
  USER_GUIDE.TABLE_JOB.ROW_SELECT
];

export { userGuideStepIndexes };

export default USER_GUIDE;
