export default {
  SEND_TERMINAL_TO_SERVER: 'SEND_TERMINAL_TO_SERVER',
  SEND_SERVER_TO_TERMINAL: 'SEND_SERVER_TO_TERMINAL',
  CLOSE_TERMINAL: 'CLOSE_TERMINAL',
  OPEN_TERMINAL: 'OPEN_TERMINAL',
  PODS_DATA: 'PODS_DATA',
  RESIZE:'RESIZE'
};
