apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: ${CICD_KUBERNETES_CERTIFICATE_AUTHORITY_DATA}
      server: https://${CICD_KUBERNETES_MASTER_IP}:6443
    name: default-cluster
contexts:
  - context:
      cluster: default-cluster
      user: default-admin
    name: default-system
current-context: default-system
kind: Config
preferences: {}
users:
  - name: default-admin
    user:
      client-certificate-data: ${CICD_CLIENT_CERTIFICATE_DATA}
      client-key-data: ${CICD_CLIENT_KEY_DATA}
